### ISSUE TITLE
Create ArgumentValidationException with message

### ISSUE THREAD

**Issue by oschrenk** [lexicalscope/jewelcli#2]
Is there an easy way to create one's own `ArgumentValidationException` with a message? I miss something like

```
    throw new ArgumentValidationException("Lorem ipsum");
```

It would help writing custom semantic validatiom.

**Comment by lexicalscope** [comment]
I've been working on the error handling and reporting for a while, I think there are a few problems with it. I will hopefully have something to release soon that should satisfy this issue.

**Comment by oschrenk** [comment]
Nice! If you got something to try out in another branch or so and are looking feedback you can leave me a message.

**Comment by lexicalscope** [comment]
The current master branch has the exception changes in, they are not backward compatible, so they are in a new package called "com.lexicalscope.jewel.cli"

The plan is to expose more details of each validation failure so that users can construct their own error and help messages if they don't want to rely on the default messages.

Hopefully, eventually the "uk.co.flamingpenguin.jewel.cli" packages will be deprecated and then removed.
